data <- read.csv("d:/coursera/Exploratory Data Analysis/data/household_power_consumption.txt", sep = ";", na.strings="?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data <- subset(data, Date >= as.Date("2007/02/01") & Date <= as.Date("2007/02/02"))
png(file = "plot3.png")
with(data, plot(Sub_metering_1, type="l", ylab="Energy sub metering", xlab = "", xaxt = "n"))
with(data, points(Sub_metering_2, col = "red", type="l"))
with(data, points(Sub_metering_3, col = "blue", type="l"))
axis(1, at = c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
legend("topright", col = c("black", "red", "blue"),  lty = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
